I use vscode to run sql

In [13]:
# Load the SQL extension
%load_ext sql

# Define the SQLite database URL (change it to your desired path)
%sql sqlite:///my_database.db


The sql extension is already loaded. To reload it, use:
  %reload_ext sql


This is the first table, we call it user_data that contain borrower information

In [14]:
%%sql

CREATE TABLE user_data (
    borrower_id INTEGER PRIMARY KEY,
    mobile TEXT,
    email TEXT,
    on_off INTEGER
);

INSERT INTO user_data (borrower_id, mobile, email, on_off)
VALUES
    (7756129, '089612345678', 'totoxxxxx@xxxxx.com', 1),
    (8108629, '08222222222', 'sahdiaxxx@xxxx.com', 1),
    (8762123, '0821201234567', 'dianfebriixxx@yyyyy.com', 1),
    (9467668, '082113434535', 'dadansimatupangxxx@yyyyy.com', 0);


 * sqlite:///my_database.db
(sqlite3.OperationalError) table user_data already exists
[SQL: CREATE TABLE user_data (
    borrower_id INTEGER PRIMARY KEY,
    mobile TEXT,
    email TEXT,
    on_off INTEGER
);]
(Background on this error at: http://sqlalche.me/e/13/e3q8)


In [15]:
%%sql

select * from user_data

 * sqlite:///my_database.db
Done.


[(7756129, '089612345678', 'totoxxxxx@xxxxx.com', 1),
 (8108629, '08222222222', 'sahdiaxxx@xxxx.com', 1),
 (8762123, '0821201234567', 'dianfebriixxx@yyyyy.com', 1),
 (9467668, '082113434535', 'dadansimatupangxxx@yyyyy.com', 0)]

The second table is loan_debt_data that contain information about debt information

In [16]:
%%sql

CREATE TABLE loan_debt_data (
    debtid INTEGER PRIMARY KEY,
    list_id INTEGER,
    list_amount INTEGER,
    agreement_id INTEGER,
    borrower_id INTEGER,
    due_date TEXT,
    principal INTEGER,
    interest INTEGER,
    service_fee INTEGER,
    payment_amount INTEGER,
    payment_time TEXT
);

INSERT INTO loan_debt_data (debtid, list_id, list_amount, agreement_id, borrower_id, due_date, principal, interest, service_fee, payment_amount, payment_time)
VALUES
    (8981902, 15380628, 700000, 15380628, 7756129, '2/15/2022 23:59', 233334, 19620, 66587, 319541, '2/16/2022 14:49'),
    (10952655, 17629126, 500000, 17629126, 7756129, '4/5/2022 23:59', 166667, 20000, 34166, 220833, '3/8/2022 8:53'),
    (11051115, 17725828, 500000, 17725828, 7756129, '2022-06-08 23:59:59', 166666, 20000, 34166, NULL, NULL),
    (11051114, 17725828, 500000, 17725828, 7756129, '2022-05-08 23:59:59', 166667, 20000, 34166, NULL, NULL),
    (11051113, 17725828, 500000, 17725828, 7756129, '2022-04-08 23:59:59', 166667, 20000, 34166, 220833, '4/5/2022 10:38'),
    (5783140, 10938199, 1600000, 10938199, 8108629, '8/1/2021 23:59', 1600000, 29458, 149295, 1778753, '7/31/2021 10:38'),
    (6073569, 11376290, 1700000, 11376290, 8108629, '8/17/2021 23:59', 1700000, 31299, 158626, 1889925, '8/17/2021 20:13'),
    (6341066, 11766427, 1000000, 11766427, 8108629, '8/31/2021 23:59', 1000000, 18411, 59453, 1077864, '8/27/2021 3:34'),
    (7192197, 12949996, 2200000, 12949996, 8108629, '10/12/2021 23:59', 2200000, 16877, 228908, 2445785, '10/12/2021 6:42'),
    (11043867, 17718508, 2600000, 17718508, 8108629, NULL, 2600000, 104000, 208000, 2912000, '4/7/2022 9:42')

UPDATE loan_debt_data
SET principal = CAST(TRIM(BOTH ' ' FROM principal) AS INTEGER);



 * sqlite:///my_database.db
(sqlite3.OperationalError) table loan_debt_data already exists
[SQL: CREATE TABLE loan_debt_data (
    debtid INTEGER PRIMARY KEY,
    list_id INTEGER,
    list_amount INTEGER,
    agreement_id INTEGER,
    borrower_id INTEGER,
    due_date TEXT,
    principal INTEGER,
    interest INTEGER,
    service_fee INTEGER,
    payment_amount INTEGER,
    payment_time TEXT
);]
(Background on this error at: http://sqlalche.me/e/13/e3q8)


In [17]:
%%sql

select * from loan_debt_data

 * sqlite:///my_database.db
Done.


[(5783140, 10938199, '1,600,000', 10938199, 8108629, '8/1/2021 23:59', '1600000', '29,458', '149,295', '1,778,753', '7/31/2021 10:38'),
 (6073569, 11376290, '1,700,000', 11376290, 8108629, '8/17/2021 23:59', '1700000', '31,299', '158,626', '1,889,925', '8/17/2021 20:13'),
 (6341066, 11766427, '1,000,000', 11766427, 8108629, '8/31/2021 23:59', '1000000', '18,411', '59,453', '1,077,864', '8/27/2021 3:34'),
 (7192197, 12949996, '2,200,000', 12949996, 8108629, '10/12/2021 23:59', '2200000', '16,877', '228,908', '2,445,785', '10/12/2021 6:42'),
 (8981902, 15380628, '700,000', 15380628, 7756129, '2/15/2022 23:59', '233334', '19,620', '66,587', '319,541', '2/16/2022 14:49'),
 (10952655, 17629126, '500,000', 17629126, 7756129, '4/5/2022 23:59', '166667', '20,000', '34,166', '220,833', '3/8/2022 8:53'),
 (11043867, 17718508, '2,600,000', 17718508, 8108629, '-', '2600000', '104,000', '208,000', '2,912,000', '4/7/2022 9:42'),
 (11051113, 17725828, '500,000', 17725828, 7756129, '2022-04-08 23:59:59', '166667', '20,000', '34,166', '220,833', '4/5/2022 10:38'),
 (11051114, 17725828, '500,000', 17725828, 7756129, '2022-05-08 23:59:59', '166667', '20,000', '34,166', '-', '-'),
 (11051115, 17725828, '500,000', 17725828, 7756129, '2022-06-08 23:59:59', '166666', '20,000', '34,166', '-', '-')]

The third table is loan_agreement_data that contain aggrement information

In [18]:
%%sql

CREATE TABLE loan_agreement_data (
    agreementid INTEGER PRIMARY KEY,
    list_id INTEGER,
    borrower_id INTEGER,
    product_id INTEGER,
    term_quantity INTEGER,
    term_unit TEXT,
    tte_document_id TEXT,
    tte_finish_time TEXT,
    extend_parameter TEXT
);

INSERT INTO loan_agreement_data (agreementid, list_id, borrower_id, product_id, term_quantity, term_unit, tte_document_id, tte_finish_time, extend_parameter)
VALUES
    (10938199, 10938199, 8108629, 10000, 14, 'D', '37969f8073d84b2fa58ff0377c14e0c2', '7/18/2021 19:07', '{"R1Msc":"1","insuServiceFeeRate":"0.01800","insuFee":"1540","insuServiceFee":"474","insuFeeRate":"0.10000"}'),
    (11376290, 11376290, 8108629, 10000, 14, 'D', NULL, NULL, '{"R1Msc":"1","insuServiceFeeRate":"0.01800","insuFee":"1540","insuServiceFee":"474","insuFeeRate":"0.10000"}'),
    (11766427, 11766427, 8108629, 10000, 14, 'D', NULL, NULL, '{"R1Msc":"1","insuServiceFeeRate":"0.01800","insuFee":"1540","insuServiceFee":"474","insuFeeRate":"0.10000"}'),
    (12949996, 12949996, 8108629, 10000, 14, 'D', NULL, NULL, '{"R1Msc":"1","insuServiceFeeRate":"0.01800","insuFee":"1540","insuServiceFee":"474","insuFeeRate":"0.10000"}'),
    (15380628, 15380628, 7756129, 10001, 1, 'M', NULL, NULL, '{"R1Msc":"1","insuServiceFeeRate":"0.0200","insuFee":"9640","insuServiceFee":"74","insuFeeRate":"0.10000"}'),
    (17629126, 17629126, 7756129, 10001, 1, 'M', '8fc06fec35704f26a5c4b066127b13e3', '3/5/2022 7:51', '{"R1Msc":"1","insuServiceFeeRate":"0.0200","insuFee":"9640","insuServiceFee":"74","insuFeeRate":"0.10000"}'),
    (17718508, 17718508, 8108629, 10001, 1, 'M', 'a667867bcfbf4d758e03573f6225697b', '3/8/2022 8:28', '{"R1Msc":"1","insuServiceFeeRate":"0.01800","insuFee":"1540","insuServiceFee":"474","insuFeeRate":"0.10000"}'),
    (17725828, 17725828, 7756129, 10001, 1, 'M', '64429a6370dd463d9c3fd61cb5af77b8', '3/8/2022 12:25', '{"R1Msc":"1","insuServiceFeeRate":"0.0200","insuFee":"9640","insuServiceFee":"74","insuFeeRate":"0.10000"}'),
    (18275607, 18275607, 9467668, 10002, 1, 'M', '343dva6370dd463d9c3fd61cb5af77b8', NULL, '{"R1Msc":"1","insuServiceFeeRate":"0.00100","insuFee":"640","insuServiceFee":"6474","insuFeeRate":"0.02000"}'),
    (18666193, 18666193, 9467668, 10002, 1, 'M', '95k06fec35704f26a5c4b066127b13e3', NULL, '{"R1Msc":"1","insuServiceFeeRate":"0.00100","insuFee":"640","insuServiceFee":"6474","insuFeeRate":"0.02000"}');


 * sqlite:///my_database.db
(sqlite3.OperationalError) table loan_agreement_data already exists
[SQL: CREATE TABLE loan_agreement_data (
    agreementid INTEGER PRIMARY KEY,
    list_id INTEGER,
    borrower_id INTEGER,
    product_id INTEGER,
    term_quantity INTEGER,
    term_unit TEXT,
    tte_document_id TEXT,
    tte_finish_time TEXT,
    extend_parameter TEXT
);]
(Background on this error at: http://sqlalche.me/e/13/e3q8)


In [19]:
%%sql

select * from loan_agreement_data

 * sqlite:///my_database.db
Done.


[(10938199, 10938199, 8108629, 10000, 14, 'D', '37969f8073d84b2fa58ff0377c14e0c2', '7/18/2021 19:07', '{"R1Msc":"1","insuServiceFeeRate":"0.01800","insuFee":"1540","insuServiceFee":"474","insuFeeRate":"0.10000"}'),
 (11376290, 11376290, 8108629, 10000, 14, 'D', None, None, '{"R1Msc":"1","insuServiceFeeRate":"0.01800","insuFee":"1540","insuServiceFee":"474","insuFeeRate":"0.10000"}'),
 (11766427, 11766427, 8108629, 10000, 14, 'D', None, None, '{"R1Msc":"1","insuServiceFeeRate":"0.01800","insuFee":"1540","insuServiceFee":"474","insuFeeRate":"0.10000"}'),
 (12949996, 12949996, 8108629, 10000, 14, 'D', None, None, '{"R1Msc":"1","insuServiceFeeRate":"0.01800","insuFee":"1540","insuServiceFee":"474","insuFeeRate":"0.10000"}'),
 (15380628, 15380628, 7756129, 10001, 1, 'M', None, None, '{"R1Msc":"1","insuServiceFeeRate":"0.0200","insuFee":"9640","insuServiceFee":"74","insuFeeRate":"0.10000"}'),
 (17629126, 17629126, 7756129, 10001, 1, 'M', '8fc06fec35704f26a5c4b066127b13e3', '3/5/2022 7:51', '{"R1Msc":"1","insuServiceFeeRate":"0.0200","insuFee":"9640","insuServiceFee":"74","insuFeeRate":"0.10000"}'),
 (17718508, 17718508, 8108629, 10001, 1, 'M', 'a667867bcfbf4d758e03573f6225697b', '3/8/2022 8:28', '{"R1Msc":"1","insuServiceFeeRate":"0.01800","insuFee":"1540","insuServiceFee":"474","insuFeeRate":"0.10000"}'),
 (17725828, 17725828, 7756129, 10001, 1, 'M', '64429a6370dd463d9c3fd61cb5af77b8', '3/8/2022 12:25', '{"R1Msc":"1","insuServiceFeeRate":"0.0200","insuFee":"9640","insuServiceFee":"74","insuFeeRate":"0.10000"}'),
 (18275607, 18275607, 9467668, 10002, 1, 'M', '343dva6370dd463d9c3fd61cb5af77b8', None, '{"R1Msc":"1","insuServiceFeeRate":"0.00100","insuFee":"640","insuServiceFee":"6474","insuFeeRate":"0.02000"}'),
 (18666193, 18666193, 9467668, 10002, 1, 'M', '95k06fec35704f26a5c4b066127b13e3', None, '{"R1Msc":"1","insuServiceFeeRate":"0.00100","insuFee":"640","insuServiceFee":"6474","insuFeeRate":"0.02000"}')]

The last table is information about product information

In [20]:
%%sql

CREATE TABLE loan_product (
    product_id INTEGER PRIMARY KEY,
    product_name TEXT
);

INSERT INTO loan_product (product_id, product_name)
VALUES
    (10000, 'Pay Day Loan'),
    (10001, 'Installment'),
    (10002, 'BNPL');


 * sqlite:///my_database.db
(sqlite3.OperationalError) table loan_product already exists
[SQL: CREATE TABLE loan_product (
    product_id INTEGER PRIMARY KEY,
    product_name TEXT
);]
(Background on this error at: http://sqlalche.me/e/13/e3q8)


In [21]:
%%sql

select * from loan_product

 * sqlite:///my_database.db
Done.


[(10000, 'Pay Day Loan'), (10001, 'Installment'), (10002, 'BNPL')]

**First Problem is to display borrowers who are still active, have loans with the product name Pay Day Loan, and Principal Loan above 1 million**

I have to set up the principal column first because it contain whitespace

In [22]:
%%sql
UPDATE loan_debt_data
SET principal = REPLACE(principal, ',', '')

UPDATE loan_debt_data
SET list_id = REPLACE(list_id, ',', '');;

 * sqlite:///my_database.db
(sqlite3.OperationalError) near "UPDATE": syntax error
[SQL: UPDATE loan_debt_data
SET principal = REPLACE(principal, ',', '')

UPDATE loan_debt_data
SET list_id = REPLACE(list_id, ',', '');]
(Background on this error at: http://sqlalche.me/e/13/e3q8)


In [23]:
%%sql
SELECT l.borrower_id, u.mobile, lp.product_name, la.list_id, l.principal FROM loan_debt_data as l
left join loan_agreement_data as la
on l.list_id = la.list_id
left join user_data as u
on l.borrower_id = u.borrower_id
left join loan_product as lp
on la.product_id = lp.product_id
WHERE CAST(TRIM(l.principal) AS INTEGER) > 1000000
and lp.product_name = 'Pay Day Loan';

 * sqlite:///my_database.db
Done.


[(8108629, '08222222222', 'Pay Day Loan', 10938199, '1600000'),
 (8108629, '08222222222', 'Pay Day Loan', 11376290, '1700000'),
 (8108629, '08222222222', 'Pay Day Loan', 12949996, '2200000')]

**Second problem is The user needs to prepare a loan report related to the Borrower with the phone number 089612345678 and Contract Number (List_ID) 17725828.**

In [24]:
%%sql
SELECT l.list_id, l.list_amount, l.agreement_id, l.borrower_id,
u.email, u.mobile, l.due_date, l.principal, l.interest,
l.service_fee, l.payment_amount, l.payment_time FROM loan_debt_data as l
left join loan_agreement_data as la
on l.list_id = la.list_id
left join user_data as u
on l.borrower_id = u.borrower_id
where u.mobile = '089612345678' 
and l.list_id = 17725828;

 * sqlite:///my_database.db
Done.


[(17725828, '500,000', 17725828, 7756129, 'totoxxxxx@xxxxx.com', '089612345678', '2022-04-08 23:59:59', '166667', '20,000', '34,166', '220,833', '4/5/2022 10:38'),
 (17725828, '500,000', 17725828, 7756129, 'totoxxxxx@xxxxx.com', '089612345678', '2022-05-08 23:59:59', '166667', '20,000', '34,166', '-', '-'),
 (17725828, '500,000', 17725828, 7756129, 'totoxxxxx@xxxxx.com', '089612345678', '2022-06-08 23:59:59', '166666', '20,000', '34,166', '-', '-')]

**Third problem is the same as the second problem but now show the tte_finish_time column and the paymen_amount is not null.**

In [25]:
%%sql
SELECT la.tte_finish_time, l.list_id, l.list_amount, l.agreement_id, l.borrower_id,
u.email, u.mobile FROM loan_debt_data as l
left join loan_agreement_data as la
on l.list_id = la.list_id
left join user_data as u
on l.borrower_id = u.borrower_id
where u.mobile = '089612345678' 
and l.list_id = 17725828
and payment_amount is not '-';

 * sqlite:///my_database.db
Done.


[('3/8/2022 12:25', 17725828, '500,000', 17725828, 7756129, 'totoxxxxx@xxxxx.com', '089612345678')]

**The fourth problem is user needs to present loan data that has been requested but the borrower has not yet electronically signed the agreement (change tte_finish_time column name to tte_status and fill null with 'No Signature')**

In [26]:
%%sql
SELECT case when la.tte_finish_time is null then 'No Signature' else la.tte_finish_time end as tte_status,
l.list_id, l.list_amount, l.agreement_id, l.borrower_id,
u.email, u.mobile FROM loan_debt_data as l
left join loan_agreement_data as la
on l.list_id = la.list_id
left join user_data as u
on l.borrower_id = u.borrower_id;

 * sqlite:///my_database.db
Done.


[('7/18/2021 19:07', 10938199, '1,600,000', 10938199, 8108629, 'sahdiaxxx@xxxx.com', '08222222222'),
 ('No Signature', 11376290, '1,700,000', 11376290, 8108629, 'sahdiaxxx@xxxx.com', '08222222222'),
 ('No Signature', 11766427, '1,000,000', 11766427, 8108629, 'sahdiaxxx@xxxx.com', '08222222222'),
 ('No Signature', 12949996, '2,200,000', 12949996, 8108629, 'sahdiaxxx@xxxx.com', '08222222222'),
 ('No Signature', 15380628, '700,000', 15380628, 7756129, 'totoxxxxx@xxxxx.com', '089612345678'),
 ('3/5/2022 7:51', 17629126, '500,000', 17629126, 7756129, 'totoxxxxx@xxxxx.com', '089612345678'),
 ('3/8/2022 8:28', 17718508, '2,600,000', 17718508, 8108629, 'sahdiaxxx@xxxx.com', '08222222222'),
 ('3/8/2022 12:25', 17725828, '500,000', 17725828, 7756129, 'totoxxxxx@xxxxx.com', '089612345678'),
 ('3/8/2022 12:25', 17725828, '500,000', 17725828, 7756129, 'totoxxxxx@xxxxx.com', '089612345678'),
 ('3/8/2022 12:25', 17725828, '500,000', 17725828, 7756129, 'totoxxxxx@xxxxx.com', '089612345678')]

**The last question is user needs to present the insurance rate and insurance fee for list_id 17629126.**

In [49]:
%%sql

select list_id, JSON_EXTRACT(extend_parameter, '$.insuFee') as ins_fee, 
JSON_EXTRACT(extend_parameter, '$.insuFeeRate') as ins_rate from loan_agreement_data
where list_id = 17629126

 * sqlite:///my_database.db
Done.


[(17629126, '9640', '0.10000')]